#apiVersion: backstage.io/v1alpha1
#kind: Component
#metadata:
#  name: backstage
#  annotations:
#    github.com/project-slug: anzaifelipe/backstage
#    backstage.io/source-location: url:https://github.com/anzaifelipe/backstage/blob/main/
#    backstage.io/managed-by-origin-location: url:https://github.com/anzaifelipe/backstage/blob/main/catalog-info.yaml
#    backstage.io/managed-by-location: url:https://github.com/anzaifelipe/backstage/blob/main/catalog-info.yaml
#spec:
#  type: other
#  lifecycle: unknown
#  owner: guests
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: agilecontent/fast-devops-modules
    backstage.io/source-location: url:https://github.com/agilecontent/fast-devops-modules/tree/main/backstage
spec:
  type: other
  lifecycle: unknown
  owner: guests