# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "agiletv-devops-terraform-files"
    encrypt = true
    key     = "CONSOLIDATION/staging/extras/ses_mib/terraform.tfstate"
    profile = "agiletv-pro"
    region  = "eu-west-1"
  }
}
